Traceback (most recent call last):
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sympy as sym
Ïƒ, Î¼, x, = sym.symbols('\sigma, \mu, x', real=True)
Ï€ = sym.pi

p = 1/(Ïƒ*sym.sqrt(2*Ï€)) * sym.exp(-(x-Î¼)**2/(2*Ïƒ**2))

podatki = {Ïƒ: 1., Î¼: 0.}

p1 = sym.plot(p.subs(podatki), (x, -3*Ïƒ.subs(podatki), +3*Ïƒ.subs(podatki)), line_color='C0', 
              label=f'$\\mu={Î¼.subs(podatki):3.2f}, \\sigma={Ïƒ.subs(podatki):3.2f}$', show=False, 
              title='Porazdelitev verjetnosti', ylabel='$p(x)$', xlabel='$x$')

podatki = {Ïƒ: 0.5, Î¼: 0.}
p2 = sym.plot(p.subs(podatki), (x, -5*Ïƒ.subs(podatki), +5*Ïƒ.subs(podatki)), line_color='C1', 
              label=f'$\\mu={Î¼.subs(podatki):3.2f}, \\sigma={Ïƒ.subs(podatki):3.2f}$', show=False)
podatki = {Ïƒ: 0.5, Î¼: 0.5}
p3 = sym.plot(p.subs(podatki), (x, -5*Ïƒ.subs(podatki), +5*Ïƒ.subs(podatki)), line_color='C2', 
              label=f'$\\mu={Î¼.subs(podatki):3.2f}, \\sigma={Ïƒ.subs(podatki):3.2f}$', show=False)
p1.extend(p2)
p1.extend(p3)
p1.legend = True
p1.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01msympy[39;00m [38;5;28;01mas[39;00m [38;5;21;01msym[39;00m
[0;32m      2[0m Ïƒ, Î¼, x, [38;5;241m=[39m sym[38;5;241m.[39msymbols([38;5;124m'[39m[38;5;124m\[39m[38;5;124msigma, [39m[38;5;124m\[39m[38;5;124mmu, x[39m[38;5;124m'[39m, real[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[0;32m      3[0m Ï€ [38;5;241m=[39m sym[38;5;241m.[39mpi

[1;31mModuleNotFoundError[0m: No module named 'sympy'
ModuleNotFoundError: No module named 'sympy'

